[tool.black]
line-length = 120

[tool.poetry]
name = "telebot"
version = "0.1.0"
description = "Updated version of SkittBot with some features from skitt_bot to work with latest version of python-telegram-bot. Now has quite a few original features as well."
authors = ["ksdfg <ksdfg123@gmail.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.10"
dnspython = "^2.1.0"
emoji = "^1.6.1"
mongoengine = "^0.23.1"
Pillow = "^9.0.1"
python-decouple = "^3.5"
python-telegram-bot = "^13.9"
spongemock = "^0.3.4"
zalgo-text = "^0.6"
hentai = "^3.2.10"
telegraph = "^2.1.0"
pydantic = "^1.9.1"

[tool.poetry.dev-dependencies]
black = "^22"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
