name: check-black-formatting
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@master
      with:
        python-version: 3.8.3
    - uses: actions/checkout@master
    - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          pip install $($HOME/.poetry/bin/poetry export --dev --without-hashes | grep black | cut -d';' -f1)
          black --check .