name: check-black-formatting
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.1
    - uses: actions/checkout@v2
    - run: |
          curl -sSL https://install.python-poetry.org | python3 -
          pip install $(poetry export --dev --without-hashes | grep black | cut -d';' -f1)
          black --check --target-version py310 .
